# Kubernetes Auto-scaling Configuration for CapSight
# Deploy with: kubectl apply -f infrastructure/kubernetes/

---
# Backend Horizontal Pod Autoscaler
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: capsight-backend-hpa
  namespace: capsight-prod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: capsight-backend
  minReplicas: 2
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  - type: Pods
    pods:
      metric:
        name: http_requests_per_second
      target:
        type: AverageValue
        averageValue: "30"
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60

---
# Frontend Auto-scaler (if using pods instead of CDN)
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: capsight-frontend-hpa
  namespace: capsight-prod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: capsight-frontend
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70

---
# Vertical Pod Autoscaler for Redis
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: capsight-redis-vpa
  namespace: capsight-prod
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: capsight-redis
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
    - containerName: redis
      minAllowed:
        cpu: 100m
        memory: 128Mi
      maxAllowed:
        cpu: 1
        memory: 4Gi
